# Generated by Django 3.0.3 on 2020-05-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytag',
            name='display_title',
            field=models.CharField(default=models.CharField(max_length=25), max_length=25),
        ),
    ]
