# Generated by Django 3.0.3 on 2020-05-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200518_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project_pics/default.png', upload_to='project_pics'),
        ),
    ]
