# Generated by Django 3.0.3 on 2020-05-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200518_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='/project_pics/default.png', upload_to='project_pics'),
        ),
    ]
