# Generated by Django 3.0.3 on 2020-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_categorytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='mysite.CategoryTag'),
        ),
    ]
